### ISSUE TITLE
The generated Java code is different

### ISSUE THREAD

**Issue by nikyotensai** [api7/ext-plugin-proto#31]
When I run `make java`,the generated  code is different from the souce.
Is there anything else I need to do？

**Comment by spacewander** [comment]
Which version of flatc do you use?

**Comment by tzssangglass** [comment]
Do you mean package name like `package io.github.api7.A6;` different the code you generated(maybe `package A6;`)?

In fact, this is a problem with flatc, which does not support specifying the package name for java code, but just uses namespace as package name.

So you need to modify the package manually after each generation.

**Comment by nikyotensai** [comment]
> Do you mean package name like `package io.github.api7.A6;` different the code you generated(maybe `package A6;`)?
> 
> In fact, this is a problem with flatc, which does not support specifying the package name for java code, but just uses namespace as package name.
> 
> So you need to modify the package manually after each generation.

Thanks.I will modify it.
